### ISSUE TITLE
Non availbale operators

### ISSUE THREAD

**Issue by axen46** [Kode-Devs/Kode#2]
1.Shift operators <<,>>...

2.Logical and, or...

3.Pre/post increament/decreament operators.

4.Power operator (**) like python is very useful in calculating powers or nth roots.

**Comment by Edumate696** [comment]
Ok @axen46 , I have decided on in ....

Firstly, both signed and unsigned shift-operators, along with power operator will be introduced in later updates.

Secondly, logical operators ( not, and, or ) is already available as **!** (not), **and** and **or** operators in Kode.

Thirdly, increment/decrement operator and bitwise operators will may or may not be added based on their implementation difficulties.

Thanking You,
@Edumate696
