### ISSUE TITLE
Library file import design

### ISSUE THREAD

**Issue by axen46** [Kode-Devs/Kode#4]
import filename;
if not found
    if online 
        if package available 
              Do you want to download? y/n
              if y
                 download starts(sizeof file if available)
                  ................................
                  complete
              if n
                  import failed
         else
               filename library file dose not exist
    else
          error
else 
     execute

**Comment by Edumate696** [comment]
@axen46  Explain it clearly ...

**Comment by axen46** [comment]
import filename;
if not found
---->if online
---->---->if package available
---->----->---->Do you want to download? y/n
---->---->----> if y
---->---->---->---->download starts(sizeof file if available)
................................
---->---->---->---->complete
---->---->---->if n
---->---->---->---->import failed
---->---->else
---->---->---->filename library file dose not exist
---->else
---->---->error
else
---->execute
